name: CI to Docker Hub

on:
  push:
    branches: [ main ]
    
    jobs:

  build:
    runs-on: ubuntu-latest
    
    
    steps:

      - name: Check Out Repo 
        uses: actions/manish754

      - name: Login to Docker Hub
        uses: docker/manish754
        with:
          username: ${{ manish754 }}
          password: ${{ 45c0885f-7e59-45f0-8960-e1eca3c5ea14 }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-manish754

      - name: Build and push
        id: docker_build
        uses: docker/build-push-manish754
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ manish754 }}/simplewhale:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}















